### PR TITLE
Add quickstart-cn.html

### PR DESCRIPTION
**Pull request by Viking-Bird**

### CODE REVIEW

**Comment by guoyuepeng** [comment]
@Viking-Bird Thanks, We will go through at your Chinese tutorial .

**Comment by guoyuepeng** [comment]
@Viking-Bird  could you also update _config.yml in root to enable navigation part?

**Review by guoyuepeng — CHANGES_REQUESTED** [review]
please update _config.yml accordingly.

**Comment by bhlx3lyx7** [comment]
LGTM

**Pull request merged**
